#!/usr/bin/env python3
"""Validate web-assets.json and generate the closed Rust embedding table."""

from __future__ import annotations

import argparse
import hashlib
import json
import string
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MANIFEST = ROOT / "web-assets.json"
PACKAGE = ROOT / "../../clients/web/pkg"
GENERATED = ROOT / "src/generated_web_assets.rs"


def load_manifest() -> dict:
    value = json.loads(MANIFEST.read_text())
    if value.get("schema_version") != "ryeos.ui.asset-manifest.v1":
        raise SystemExit("unsupported browser asset manifest schema")
    if not isinstance(value.get("ui_binding_revision"), str):
        raise SystemExit("browser asset manifest lacks ui_binding_revision")
    assets = value.get("assets")
    if not isinstance(assets, list) or not assets:
        raise SystemExit("browser asset manifest must contain assets")
    return value


def validate(manifest: dict) -> None:
    routes: set[str] = set()
    filenames: set[str] = set()
    known_routes = {asset["route"] for asset in manifest["assets"]}
    for asset in manifest["assets"]:
        route = asset["route"]
        filename = asset["filename"]
        if route in routes or filename in filenames:
            raise SystemExit(f"duplicate asset route or filename: {route} / {filename}")
        routes.add(route)
        filenames.add(filename)
        if route != "/ui" and route != f"/ui/assets/{filename}":
            raise SystemExit(f"non-canonical asset route: {route}")
        if Path(filename).name != filename:
            raise SystemExit(f"asset filename must be one path component: {filename}")
        if asset["cache"] not in {"no-cache", "public, max-age=31536000, immutable"}:
            raise SystemExit(f"unsupported cache policy for {route}: {asset['cache']}")
        if len(asset["sha256"]) != 64 or any(
            character not in string.hexdigits for character in asset["sha256"]
        ):
            raise SystemExit(f"invalid SHA-256 for {route}")
        if not isinstance(asset["imports"], list):
            raise SystemExit(f"imports must be a list for {route}")
        path = PACKAGE / filename
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if digest != asset["sha256"]:
            raise SystemExit(
                f"asset digest mismatch for {filename}: manifest={asset['sha256']} actual={digest}"
            )
        for imported in asset["imports"]:
            if imported not in known_routes:
                raise SystemExit(f"{route} imports unregistered asset {imported}")

    packaged = {
        path.name
        for path in PACKAGE.iterdir()
        if path.is_file()
        and path.suffix in {".html", ".js", ".css", ".wasm", ".png", ".svg", ".ico"}
    }
    if packaged != filenames:
        raise SystemExit(
            "packaged browser asset inventory differs from manifest: "
            f"unregistered={sorted(packaged - filenames)} missing={sorted(filenames - packaged)}"
        )


def render(manifest: dict) -> str:
    lines = [
        "// @generated by generate_asset_registry.py; do not edit by hand.",
        f'pub(super) const ASSET_MANIFEST_SCHEMA: &str = "{manifest["schema_version"]}";',
        f'pub(super) const ASSET_UI_BINDING_REVISION: &str = "{manifest["ui_binding_revision"]}";',
        "pub(super) static WEB_ASSETS: &[WebAssetEntry] = &[",
    ]
    for asset in manifest["assets"]:
        imports = ", ".join(json.dumps(value) for value in asset["imports"])
        lines.extend(
            [
                "    WebAssetEntry {",
                f'        route: {json.dumps(asset["route"])},',
                f'        filename: {json.dumps(asset["filename"])},',
                f'        content_type: {json.dumps(asset["mime"])},',
                f'        cache_control: {json.dumps(asset["cache"])},',
                f'        sha256: {json.dumps(asset["sha256"])},',
                f'        imports: &[{imports}],',
                f'        bytes: include_bytes!("../../../clients/web/pkg/{asset["filename"]}"),',
                "    },",
            ]
        )
    lines.extend(["];"])
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--refresh-digests", action="store_true")
    args = parser.parse_args()
    if args.check and args.refresh_digests:
        raise SystemExit("--check and --refresh-digests are mutually exclusive")
    manifest = load_manifest()
    if args.refresh_digests:
        for asset in manifest["assets"]:
            asset["sha256"] = hashlib.sha256(
                (PACKAGE / asset["filename"]).read_bytes()
            ).hexdigest()
        MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")
    validate(manifest)
    expected = render(manifest)
    if args.check:
        if not GENERATED.exists() or GENERATED.read_text() != expected:
            raise SystemExit("generated browser asset registry is stale")
    else:
        GENERATED.write_text(expected)


if __name__ == "__main__":
    main()
