# ryeos:signed:2026-05-31T03:43:12Z:d873921aa52b31531c01189ef908a2b0a6ddeff7f9ef51b840a1dbc004adaa78:++No1ufrg7Q23I9zIOexuUAXeQZF2LLpWO9J/0ItmM1qaQOiEXfdyFBeS/vzHSna6HR6gmAe0/5+lpPw0SR4DA==:f168bc6752bd022d89a6778a8d2239b302f453d7e862770ed7ed1093c96363d1
kind: service
endpoint: remote.configure
required_caps: ["ryeos.execute.service.remote.configure"]
schema:
  remote: string?
  url: string?
  descriptor: string?
description: "Add or update a remote node configuration, optionally from a descriptor trust pin"
