# ryeos:signed:2026-08-11T02:28:23Z:320d6b94702b22c40475c9486b4c2734ad6115f2264a8dbe535725921237317a:enDnoe3UkRMEUWvaavSBtoYDbwnuiMFaLd7+ujVfthQO5NHZyitZrq8wZmGjmJJOsW9DhvQySKJve3kOQgudCw==:741a8bc609b398aaec0685e5aefb682faf5129a66bd192f888d23bb642c18eea
category: ryeos/core
name: graph-effective-validator
kind: handler
serves: effective_validator
binary_ref: bin/x86_64-unknown-linux-gnu/ryeos-graph-effective-validator
abi_version: "v2"
required_caps: []
description: "Strict semantic validator for a fully composed graph"
