// @generated by generate_asset_registry.py; do not edit by hand.
pub(super) const ASSET_MANIFEST_SCHEMA: &str = "ryeos.ui.asset-manifest.v1";
pub(super) const ASSET_UI_BINDING_REVISION: &str = "ryeos.ui.binding.v4";
pub(super) static WEB_ASSETS: &[WebAssetEntry] = &[
    WebAssetEntry {
        route: "/ui",
        filename: "index.html",
        content_type: "text/html; charset=utf-8",
        cache_control: "no-cache",
        sha256: "ef90a265205b429fac3e265b5e6cc42407b7bd544ca9577427296d0f1e078124",
        imports: &["/ui/assets/ryeos_ui.css", "/ui/assets/ryeos_ui.js"],
        bytes: include_bytes!("../../../clients/web/pkg/index.html"),
    },
    WebAssetEntry {
        route: "/ui/assets/ryeos_ui.js",
        filename: "ryeos_ui.js",
        content_type: "application/javascript; charset=utf-8",
        cache_control: "no-cache",
        sha256: "9c4018519f13764212f66a4f0b774f1453d1838fceebd6bfe7beb08fb98d1d71",
        imports: &["/ui/assets/ryeos_three.js", "/ui/assets/ryeos_web.js", "/ui/assets/ryeos_web_bg.wasm"],
        bytes: include_bytes!("../../../clients/web/pkg/ryeos_ui.js"),
    },
    WebAssetEntry {
        route: "/ui/assets/ryeos_ui.css",
        filename: "ryeos_ui.css",
        content_type: "text/css; charset=utf-8",
        cache_control: "no-cache",
        sha256: "ccd33287cf41e6cfc83d429e2828bed67d42da797945d0333eb65d699a519528",
        imports: &[],
        bytes: include_bytes!("../../../clients/web/pkg/ryeos_ui.css"),
    },
    WebAssetEntry {
        route: "/ui/assets/ryeos_three.js",
        filename: "ryeos_three.js",
        content_type: "application/javascript; charset=utf-8",
        cache_control: "no-cache",
        sha256: "ab99d4b846e921f4d1a395b793ffc236b9450ee84231cf2d814cf372b93902d3",
        imports: &[],
        bytes: include_bytes!("../../../clients/web/pkg/ryeos_three.js"),
    },
    WebAssetEntry {
        route: "/ui/assets/ryeos_web.js",
        filename: "ryeos_web.js",
        content_type: "application/javascript; charset=utf-8",
        cache_control: "no-cache",
        sha256: "4fe175316400c649ea673834acb9ac85b26a1d3e96ba8799034c78e23ae2018b",
        imports: &["/ui/assets/ryeos_web_bg.wasm"],
        bytes: include_bytes!("../../../clients/web/pkg/ryeos_web.js"),
    },
    WebAssetEntry {
        route: "/ui/assets/ryeos_web_bg.wasm",
        filename: "ryeos_web_bg.wasm",
        content_type: "application/wasm",
        cache_control: "no-cache",
        sha256: "eb67e7b40e9b5799837a96e02b37310f2a3b3967ee961fc6fb219143b8c55624",
        imports: &[],
        bytes: include_bytes!("../../../clients/web/pkg/ryeos_web_bg.wasm"),
    },
];
