// @generated by generate_asset_registry.py; do not edit by hand.
pub(super) const ASSET_MANIFEST_SCHEMA: &str = "ryeos.ui.asset-manifest.v1";
pub(super) const ASSET_UI_BINDING_REVISION: &str = "ryeos.ui.binding.v5";
pub(super) static WEB_ASSETS: &[WebAssetEntry] = &[
    WebAssetEntry {
        route: "/ui",
        filename: "index.html",
        content_type: "text/html; charset=utf-8",
        cache_control: "no-cache",
        sha256: "ef90a265205b429fac3e265b5e6cc42407b7bd544ca9577427296d0f1e078124",
        imports: &["/ui/assets/ryeos_ui.css", "/ui/assets/ryeos_ui.js"],
        bytes: include_bytes!("../../../clients/web/pkg/index.html"),
    },
    WebAssetEntry {
        route: "/ui/assets/ryeos_ui.js",
        filename: "ryeos_ui.js",
        content_type: "application/javascript; charset=utf-8",
        cache_control: "no-cache",
        sha256: "a06591e95d4546fd54d9e329fd5647681521a3999e5fa18e4c69aa2de5ceb45e",
        imports: &[
            "/ui/assets/ryeos_three.js",
            "/ui/assets/ryeos_web.js",
            "/ui/assets/ryeos_web_bg.wasm",
        ],
        bytes: include_bytes!("../../../clients/web/pkg/ryeos_ui.js"),
    },
    WebAssetEntry {
        route: "/ui/assets/ryeos_ui.css",
        filename: "ryeos_ui.css",
        content_type: "text/css; charset=utf-8",
        cache_control: "no-cache",
        sha256: "eb26a439e40e3ab54b5836df9253126e0222182efd9bdc1b0206590762bf1365",
        imports: &[],
        bytes: include_bytes!("../../../clients/web/pkg/ryeos_ui.css"),
    },
    WebAssetEntry {
        route: "/ui/assets/ryeos_three.js",
        filename: "ryeos_three.js",
        content_type: "application/javascript; charset=utf-8",
        cache_control: "no-cache",
        sha256: "914899ca99c9e5aba19e97a9df9bc3e6895c524159133bf591e9b66e7d24eb62",
        imports: &[],
        bytes: include_bytes!("../../../clients/web/pkg/ryeos_three.js"),
    },
    WebAssetEntry {
        route: "/ui/assets/ryeos_web.js",
        filename: "ryeos_web.js",
        content_type: "application/javascript; charset=utf-8",
        cache_control: "no-cache",
        sha256: "4f73526ceaaca1e7c991d0d37d65543b933f6d2e49dcb14af32b7552790c0474",
        imports: &["/ui/assets/ryeos_web_bg.wasm"],
        bytes: include_bytes!("../../../clients/web/pkg/ryeos_web.js"),
    },
    WebAssetEntry {
        route: "/ui/assets/ryeos_web_bg.wasm",
        filename: "ryeos_web_bg.wasm",
        content_type: "application/wasm",
        cache_control: "no-cache",
        sha256: "e93086e1ce638e871913c343de765229468a09ab1e71e15066f3a0b9ecd32059",
        imports: &[],
        bytes: include_bytes!("../../../clients/web/pkg/ryeos_web_bg.wasm"),
    },
];
