import type {
  BrowserViewport,
  RyeOsEffectResult,
  RyeOsEnvelope,
  RyeOsEvent,
  RyeOsKeyEvent,
  RyeOsUiEvent,
  SeatEvent,
} from "../generated";

export interface RyeOsKeyOutcome {
  readonly handled: boolean;
  readonly envelope: RyeOsEnvelope;
}

/** Exact callable surface generated by wasm-bindgen for the Rust UI core. */
export interface RyeOsWasmApi {
  default(input: { module_or_path: string | URL | Request | BufferSource }): Promise<unknown>;
  ryeos_start(session: unknown, viewport: BrowserViewport, nowMs: bigint): RyeOsEnvelope;
  ryeos_dispatch(event: RyeOsEvent): RyeOsEnvelope;
  ryeos_apply_effect_result(result: RyeOsEffectResult): RyeOsEnvelope;
  ryeos_key(event: RyeOsKeyEvent): RyeOsKeyOutcome;
  ryeos_seat_events(): SeatEvent[];
  ryeos_replay_seat_events(events: unknown[]): RyeOsEnvelope;
  ryeos_layout_preference_key(): string;
  ryeos_export_layout_preferences(): string;
  ryeos_restore_layout_preferences(encoded: string): RyeOsEnvelope;
  ryeos_export_active_view_set_template(id: string, name: string): string;
  ryeos_open_saved_view_set_template(encoded: string): RyeOsEnvelope;
}

export async function loadWasm(): Promise<RyeOsWasmApi> {
  const specifier = "/ui/assets/ryeos_web.js";
  const module: unknown = await import(/* @vite-ignore */ specifier);
  if (!isWasmApi(module)) throw new Error("installed RyeOS WASM module has an invalid export surface");
  return module;
}

function isWasmApi(value: unknown): value is RyeOsWasmApi {
  if (typeof value !== "object" || value === null) return false;
  const exports = value as Record<string, unknown>;
  return [
    "default", "ryeos_start", "ryeos_dispatch", "ryeos_apply_effect_result",
    "ryeos_key", "ryeos_seat_events", "ryeos_replay_seat_events",
    "ryeos_layout_preference_key", "ryeos_export_layout_preferences",
    "ryeos_restore_layout_preferences",
    "ryeos_export_active_view_set_template", "ryeos_open_saved_view_set_template",
  ].every((name) => typeof exports[name] === "function");
}

export type DispatchUi = (event: RyeOsUiEvent) => void;
