# ryeos:signed:2026-08-13T07:32:09Z:1aa3aed822a01ee2567dc421963fd8f8b42bf4ceb51b02a92de3120e090145a4:puZGl31TBYEgTCiyOJlaMbXOs0KvJLCNdhFgAAsxxeKJJlgsG2qY6dFq6RngFpijUgGFL5bwbuXJD/KRordNAw==:741a8bc609b398aaec0685e5aefb682faf5129a66bd192f888d23bb642c18eea
category: ryeos/standard
name: directive-launch
kind: handler
serves: launch_preparer
binary_ref: bin/x86_64-unknown-linux-gnu/ryeos-directive-launch-preparer
abi_version: "v3"
required_caps: []
description: "Pure directive model/provider launch preparer"
