# rye:signed:2026-04-20T06:00:53Z:6712f25daede6b85480eff59f3ed2bc5f9e0711bca1ed0c5116201986dabefbc:UtZPsCq0MIiaI-9SnQJ1IRUcSVpVSCHHjYNLoxMacvfGmvFWYLaRg4UDr9V58syAyHpUMykilRboLTfVzBWACA:4b987fd4e40303ac
category: "engine/kinds/directive"
version: "1.0.0"
location:
  directory: directives
execution:
  default_executor_id: "native:directive-runtime"
resolution:
  - resolve_extends_chain
  - resolve_provider
  - preload_tool_schemas
formats:
  - extensions: [".md"]
    parser_id: markdown/xml
    signature:
      prefix: "<!--"
      suffix: "-->"
metadata:
  rules:
    name:
      from: path
      key: name
    version:
      from: path
      key: version
    description:
      from: path
      key: description
    category:
      from: path
      key: category
