"""Bind tinygrad kernel lowering to the admitted compiler realization."""

from __future__ import annotations

import importlib
import os
import subprocess
import tempfile
from pathlib import Path


def install_admitted_compiler(workspace: Path) -> None:
    workspace = workspace.resolve(strict=True)
    loader = (workspace / "runtime" / "lib" / "ld-musl-x86_64.so.1").resolve(strict=True)
    runtime_lib = (workspace / "runtime" / "lib").resolve(strict=True)
    compiler = (workspace / "toolchain" / "bin" / "clang").resolve(strict=True)
    linker = (workspace / "toolchain" / "bin" / "ld.lld").resolve(strict=True)
    compiler_lib = (workspace / "toolchain" / "lib").resolve(strict=True)
    compiler_support = (
        workspace
        / "toolchain"
        / "lib"
        / "clang"
        / "20"
        / "lib"
        / "x86_64-alpine-linux-musl"
        / "libclang_rt.builtins-x86_64.a"
    ).resolve(strict=True)
    scratch = (workspace / "scratch").resolve(strict=True)
    for path in (
        loader,
        runtime_lib,
        compiler,
        linker,
        compiler_lib,
        compiler_support,
        scratch,
    ):
        if path != workspace and workspace not in path.parents:
            raise RuntimeError("compiler dependency escaped the admitted workspace")
    if not all(path.is_file() for path in (loader, compiler, linker, compiler_support)):
        raise RuntimeError("admitted compiler executable closure is incomplete")

    generated_libc = (
        workspace / "tinygrad" / "tinygrad" / "runtime" / "autogen" / "libc.py"
    ).resolve(strict=True)
    if workspace not in generated_libc.parents:
        raise RuntimeError("generated tinygrad libc module escaped the admitted workspace")
    autogen = importlib.import_module("tinygrad.runtime.autogen")
    libc_module = importlib.import_module("tinygrad.runtime.autogen.libc")
    if Path(libc_module.__file__).resolve(strict=True) != generated_libc:
        raise RuntimeError("tinygrad libc module did not come from admitted generated bytes")
    # `compiler_cpu` imports this attribute through tinygrad's lazy autogen
    # package. Supplying the admitted generated module explicitly prevents the
    # fallback generator from consulting dpkg, headers, or the network.
    setattr(autogen, "libc", libc_module)

    from tinygrad.runtime.support.compiler_cpu import ClangCompiler
    from tinygrad.runtime.support import elf

    # tinygrad's object loader normally asks the host dynamic-linker search path
    # to resolve compiler support symbols. That is ambient execution authority.
    # All compiler builtins are linked into each object from the admitted archive;
    # anything still undefined is rejected rather than searched for on the node.
    def reject_ambient_symbol(symbol: str, _libraries: list[str]) -> int:
        raise RuntimeError(
            f"kernel requested symbol {symbol!r} outside the admitted compiler closure"
        )

    elf.link_sym = reject_ambient_symbol

    def compile_to_obj(self: ClangCompiler, source: str) -> bytes:
        environment = {
            "HOME": os.environ["HOME"],
            "TMPDIR": os.environ["TMPDIR"],
            "LANG": "C",
            "LC_ALL": "C",
            "PATH": "",
            "SOURCE_DATE_EPOCH": "0",
        }
        with tempfile.TemporaryDirectory(dir=scratch, prefix="kernel-") as temporary:
            temporary_path = Path(temporary)
            compiled = temporary_path / "kernel.o"
            linked = temporary_path / "kernel-linked.o"
            subprocess.run(
                [
                    str(loader),
                    "--library-path",
                    f"{compiler_lib}:{runtime_lib}",
                    str(compiler),
                    "-c",
                    "-x",
                    "c",
                    "-O2",
                    "-fPIC",
                    "-ffreestanding",
                    "-fno-math-errno",
                    "-nostdlib",
                    "-fno-ident",
                    f"--target={self.arch}-none-unknown-elf",
                    *self.args,
                    "-",
                    "-o",
                    str(compiled),
                ],
                input=source.encode("utf-8"),
                cwd=scratch,
                env=environment,
                check=True,
            )
            subprocess.run(
                [
                    str(loader),
                    "--library-path",
                    f"{compiler_lib}:{runtime_lib}",
                    str(linker),
                    "-r",
                    "--strip-debug",
                    str(compiled),
                    str(compiler_support),
                    "-o",
                    str(linked),
                ],
                cwd=scratch,
                env=environment,
                check=True,
            )
            return linked.read_bytes()

    ClangCompiler.compile_to_obj = compile_to_obj
