# rye:signed:2026-05-01T13:29:30Z:9fbedb2e5df13ed3846cfe26d78e153f8a8f58346860fe5f13bcef418e9c5385:z+L9oGzsPmNHwIZaYLsBOCGVHBbzV7CuUWtzRqGEAnh+/VNvJF1XenstOVKljhS7GvxsDWAsS7Rxw0kKV2DpBQ==:09674c8998e9dd01bfc40ec9f8c4b6b2c1bd01333842582a9c34b3c7db5aa86c
kind: config
category: "cli"
tokens: ["events", "chain-replay"]
description: "Replay events across an entire chain (root and descendants)."
execute: service:events/chain_replay