# rye:signed:2026-04-29T02:47:24Z:b0317c980978211a8cfa1770f34ef5d2d214fd1cea9e2b7a61353b99283f2be5:phak+U5OnBnPthD9RLjF1b/8etMuzFDgCeMqxcMtoHzKOAau+XlK+s+lNFV3rqimoiUrWoWtnNQJTjCSjAMBCg==:8f4c002347bcb25b80e32a9f5ba7064638f0d372b8dd5cfbff3da765f94ef4bb
kind: config
category: "cli"
tokens: ["thread", "chain"]
description: "Get the parent chain for a thread (root -> ... -> thread)."
execute: service:threads/chain