# ryeos:signed:2026-05-23T09:45:28Z:1039096521b427bbcf81055af0a95d7f31068ddbf5bbf4b82817cdedbe61e480:d/lwpXa7gCr1d8yEzRqHL7bHQxmnagVTyR9WToeRNOXtk3/pYVSqSD6bmKCwiyCB4T2IQsL8CsT0XBDHL/0+AA==:f168bc6752bd022d89a6778a8d2239b302f453d7e862770ed7ed1093c96363d1
category: ryeos/core
name: yaml-document
kind: handler
serves: parser
binary_ref: bin/x86_64-unknown-linux-gnu/rye-parser-yaml-document
abi_version: "v1"
required_caps: []
description: "YAML document parser handler"
