# rye:signed:2026-05-03T02:08:25Z:3eeec024b1bd7033358e8e29db6ed1716fd6762b909f85ea8b5cd9c1411cf580:1ADr061OBw35HlMhsSwZoy6PcRbtd+g1Mggs8ODLwbTWEcBYkLh5qOKBENLKEWg/0p4quiU6M3ZYKYCcbpiBDA==:09674c8998e9dd01bfc40ec9f8c4b6b2c1bd01333842582a9c34b3c7db5aa86c
category: rye/core
name: yaml-document
kind: handler
serves: parser
binary_ref: bin/x86_64-unknown-linux-gnu/rye-parser-yaml-document
abi_version: "v1"
required_caps: []
description: "YAML document parser handler"
