//! Integration test: `run_publish` is idempotent.
//!
//! Two consecutive publishes of the same bundle with the same key and
//! no source content changes must produce zero file changes (zero git
//! diff). This is the acceptance contract for the incremental publish
//! design: every signing path checks body hash + signer fingerprint +
//! signature validity before writing.
//!
//! Prerequisites:
//!   - `bundles/core/` must exist and contain a publishable bundle
//!   - `.dev-keys/PUBLISHER_DEV.pem` must exist (dev signing key)
//!
//! This test is intentionally slow (~20-30s) because it exercises the
//! full publish pipeline including CAS rebuild and kind schema bootstrap.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use lillux::crypto::{DecodePrivateKey, SigningKey};

static HANDLER_BINS_BUILD: OnceLock<()> = OnceLock::new();

fn host_triple() -> String {
    let output = std::process::Command::new("rustc")
        .args(["-vV"])
        .output()
        .expect("rustc -vV");
    let stdout = String::from_utf8_lossy(&output.stdout);
    stdout
        .lines()
        .find(|line| line.starts_with("host:"))
        .expect("host triple in rustc -vV")
        .strip_prefix("host:")
        .unwrap()
        .trim()
        .to_string()
}

fn workspace_root() -> PathBuf {
    ryeos_engine::test_support::workspace_root()
}

fn dev_key_path() -> PathBuf {
    workspace_root().join(".dev-keys").join("PUBLISHER_DEV.pem")
}

fn source_bundle() -> PathBuf {
    workspace_root().join("bundles").join("core")
}

/// Snapshot every signable source file's SHA-256 hash under a directory.
///
/// Snapshot bundle file SHA-256 hashes while excluding only binary sidecars
/// that are deliberately regenerated by the CAS rebuild.
fn snapshot_file_hashes(root: &Path) -> BTreeMap<String, String> {
    let mut hashes = BTreeMap::new();
    walk_files(root, &mut hashes, root);
    hashes
}

fn walk_files(dir: &Path, out: &mut BTreeMap<String, String>, base: &Path) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // Skip .git
            if path.file_name().and_then(|n| n.to_str()) == Some(".git") {
                continue;
            }
            walk_files(&path, out, base);
        } else if path.is_file() {
            // Per-triple and per-binary sidecars are generated as part of
            // CAS rebuild. Do not skip binaries themselves — accidental
            // binary rewrites should be visible to this test.
            if let Some(name) = path.file_name().and_then(|n| n.to_str())
                && (name == "MANIFEST.json" || name.ends_with(".item_source.json"))
            {
                continue;
            }
            let rel = path
                .strip_prefix(base)
                .unwrap_or(&path)
                .to_string_lossy()
                .to_string();
            let content = std::fs::read(&path).unwrap_or_default();
            let hash = lillux::sha256_hex(&content);
            out.insert(rel, hash);
        }
    }
}

fn load_dev_signing_key() -> SigningKey {
    let pem = std::fs::read_to_string(dev_key_path())
        .expect("dev signing key not found — run from workspace root");
    SigningKey::from_pkcs8_pem(&pem).expect("parse dev signing key")
}

fn copy_dir_recursive(src: &Path, dst: &Path) {
    std::fs::create_dir_all(dst).unwrap();
    for entry in std::fs::read_dir(src).unwrap() {
        let entry = entry.unwrap();
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dst_path);
        } else {
            std::fs::copy(&src_path, &dst_path).unwrap();
        }
    }
}

fn target_release_dir() -> PathBuf {
    if let Some(dir) = std::env::var_os("CARGO_TARGET_DIR") {
        PathBuf::from(dir).join("release")
    } else {
        workspace_root().join("target").join("release")
    }
}

fn ensure_handler_bins_built() -> PathBuf {
    let release_dir = target_release_dir();
    let required = [
        "rye-parser-yaml-document",
        "rye-parser-yaml-header-document",
        "rye-parser-regex-kv",
        "rye-composer-identity",
        "ryeos-direct-execution-evidence",
        "ryeos-core-tools",
        "ryeos-session-exec",
        "ryeos-worker-execution-launch-preparer",
        "ryeos-worker-execution-runtime",
        "ryeos-structured-session-bridge",
        "ryeos-lillux-isolation-adapter",
    ];

    if required.iter().all(|name| release_dir.join(name).is_file()) {
        return release_dir;
    }

    HANDLER_BINS_BUILD.get_or_init(|| {
        let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
        let status = std::process::Command::new(cargo)
            .args([
                "build",
                "--release",
                "-p",
                "ryeos-handler-bins",
                "--bins",
                "-p",
                "ryeos-core-tools",
                "-p",
                "ryeos-session-exec",
                "-p",
                "ryeos-structured-session",
                "-p",
                "ryeos-lillux-isolation-adapter",
            ])
            .current_dir(workspace_root())
            .status()
            .expect("spawn release build for core bundle binaries");
        assert!(
            status.success(),
            "release build for core bundle binaries failed"
        );
    });

    release_dir
}

fn copy_executable(src: &Path, dst: &Path) {
    std::fs::copy(src, dst).unwrap_or_else(|e| {
        panic!(
            "copy executable {} -> {} failed: {e}",
            src.display(),
            dst.display()
        )
    });
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(dst).unwrap().permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(dst, perms).unwrap();
    }
}

fn stage_real_core_binaries(bundle: &Path) {
    let triple = host_triple();
    if triple != "x86_64-unknown-linux-gnu" {
        eprintln!(
            "skipping binary staging: core descriptors target x86_64-unknown-linux-gnu, host is {triple}"
        );
        return;
    }

    let bin_root = bundle.join(ryeos_engine::AI_DIR).join("bin");
    let bin_dir = bin_root.join(&triple);
    let _ = std::fs::remove_dir_all(&bin_root);
    std::fs::create_dir_all(&bin_dir).unwrap();

    // Preserve the complete checked-in executable closure. The focused
    // handler build below refreshes the binaries it owns, while handlers from
    // other packages (for example the worker launch preparer) remain available
    // to registry validation.
    let source_bin_dir = source_bundle()
        .join(ryeos_engine::AI_DIR)
        .join("bin")
        .join(&triple);
    for entry in std::fs::read_dir(&source_bin_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_file()
            && path.extension().and_then(|extension| extension.to_str()) != Some("json")
        {
            copy_executable(&path, &bin_dir.join(entry.file_name()));
        }
    }

    let release_dir = ensure_handler_bins_built();
    for name in [
        "rye-parser-yaml-document",
        "rye-parser-yaml-header-document",
        "rye-parser-regex-kv",
        "rye-composer-identity",
        "ryeos-direct-execution-evidence",
        "ryeos-core-tools",
        "ryeos-session-exec",
        "ryeos-worker-execution-launch-preparer",
        "ryeos-worker-execution-runtime",
        "ryeos-structured-session-bridge",
        "ryeos-lillux-isolation-adapter",
    ] {
        copy_executable(&release_dir.join(name), &bin_dir.join(name));
    }
}

fn run_publish_once(
    bundle_dir: &Path,
    key: &SigningKey,
) -> ryeos_core_tools::actions::publish::PublishReport {
    let opts = ryeos_core_tools::actions::publish::PublishOptions {
        bundle_source: bundle_dir.to_path_buf(),
        registry_roots: vec![bundle_dir.to_path_buf()], // core is its own registry
        signing_key: key.clone(),
        base_trust_store: None,
        owner: "test".to_string(),
        name: None,
        skip_unsignable: false,
        allow_namespace_mismatch: false,
        emit_trust_doc: false,
    };
    ryeos_core_tools::actions::publish::run_publish(&opts)
        .unwrap_or_else(|e| panic!("publish failed: {e:#}"))
}

#[test]
fn publish_twice_produces_zero_diff() {
    let source = source_bundle();
    if !source.join(ryeos_engine::AI_DIR).is_dir() {
        eprintln!("skipping: bundles/core not found");
        return;
    }
    let key = load_dev_signing_key();

    // Create a temp copy to avoid mutating the source tree
    let tmp = tempfile::tempdir().unwrap();
    let bundle = tmp.path().join("core");
    copy_dir_recursive(&source, &bundle);
    stage_real_core_binaries(&bundle);

    // Run 1: initial publish
    let _report1 = run_publish_once(&bundle, &key);

    // Snapshot all file hashes
    let hashes1 = snapshot_file_hashes(&bundle);

    // Run 2: re-publish with no content changes
    let report2 = run_publish_once(&bundle, &key);

    // Snapshot again
    let hashes2 = snapshot_file_hashes(&bundle);

    // Assert: no file bytes changed
    assert_eq!(
        hashes1, hashes2,
        "second publish changed file contents — publish is not idempotent"
    );

    // Assert: report shows zero signed items on second run
    assert_eq!(
        report2.bootstrap_signed, 0,
        "bootstrap_signed should be 0 on second run, got {}",
        report2.bootstrap_signed
    );
    assert!(
        report2.sign_report.signed.is_empty(),
        "sign_report.signed should be empty on second run, got: {:?}",
        report2.sign_report.signed
    );
    assert!(
        !report2.manifest_changed,
        "manifest_changed should be false on second run"
    );
    assert!(
        report2.rebuild_report.is_some(),
        "binary-owning bundle should rebuild the binary CAS manifest"
    );
    assert!(
        !report2.binary_rebuild_skipped,
        "binary-owning bundle should not report skipped binary rebuild"
    );

    assert!(
        report2.sign_report.failed.is_empty(),
        "sign_report.failed should be empty on second run, got: {:?}",
        report2.sign_report.failed
    );

    // Basic sanity: second run validated everything
    assert!(
        report2.bootstrap_validated + report2.sign_report.validated.len() > 0,
        "second run should have validated existing items"
    );
}

#[test]
fn publish_rotates_bundle_manifest_before_source_unit_validation() {
    let source = source_bundle();
    if !source.join(ryeos_engine::AI_DIR).is_dir() {
        eprintln!("skipping: bundles/core not found");
        return;
    }

    // The checked-in core generation belongs to the development publisher.
    // A distinct key models the official release publisher without admitting
    // the predecessor into its node trust.
    let replacement_key = SigningKey::from_bytes(&[99u8; 32]);
    let tmp = tempfile::tempdir().unwrap();
    let bundle = tmp.path().join("core");
    copy_dir_recursive(&source, &bundle);
    stage_real_core_binaries(&bundle);

    let report = run_publish_once(&bundle, &replacement_key);

    assert!(
        report.sign_report.failed.is_empty(),
        "publisher rotation retained predecessor manifest authority: {:?}",
        report.sign_report.failed
    );
    assert!(report.manifest_changed);

    let manifest =
        std::fs::read_to_string(bundle.join(ryeos_engine::AI_DIR).join("manifest.yaml")).unwrap();
    let signature = lillux::signature::parse_signature_line(
        manifest.lines().next().unwrap_or_default(),
        "#",
        None,
    )
    .expect("published manifest signature");
    assert_eq!(
        signature.signer_fingerprint,
        lillux::signature::compute_fingerprint(&replacement_key.verifying_key())
    );
}
