# rye:signed:2026-04-10T00:57:18Z:90994aa7584ee4e923ca6790bf75001b42bb94ad80218d6a2b503ae8fb2c5c0c:lXv6Ij9FsIaE_IeZQfv3mboTGQBxoiBV6klnL3LDx4QXh4snLcE3Y3I8E8HRVDiQjuI4QBnt-8osQiSCZrS0CA:4b987fd4e40303ac
version: "1.0.0"
tool_type: config-schema
executor_id: null
category: rye/core/remote
description: "Schema for cas/manifest.yaml — sync policy and exclusions"

target_config: cas/manifest.yaml

schema:
  type: object
  properties:
    sync:
      type: object
      properties:
        include:
          type: array
          items:
            type: string
        exclude:
          type: array
          items:
            type: string
